<?php

return [
    "Souviens-toi de tes erreurs, et la clémence guidera tes jugements.  Romain Guilleaumes  (Chapitre 48)",
    "Si on ne suppose pas que les hommes ont tous la même intelligence, et l'ont toute, il n'y a plus ni vérité ni erreur.  Emile Chartier, dit Alain  (Cahiers de Lorient)",
    "L'erreur de Descartes est de meilleure qualité que la vérité d'un pédant.  Emile Chartier, dit Alain  (Propos d'un Normand)",
    "Il y a des erreurs qui contiennent une autre vérité.  Erri de Luca  (Trois chevaux)",
    "Ce que nous dénommons vérité n'est qu'une élimination d'erreurs.  Georges Clemenceau  (Aux embuscades de la vie)",
    "L'erreur est la règle ; la vérité est l'accident de l'erreur.  Georges Duhamel  (Le Notaire du Havre)",
    "Il y a des esprit qui vont à l'erreur par toutes les vérités ; il en est de plus heureux qui vont aux grandes vérités par toutes les erreurs.  Joseph Joubert  (Carnets)",
    "Une erreur n'est souvent qu'une vérité coupée en herbe.  Jules Romains  (Lucienne)",
    "Aime la vérité, mais pardonne à l'erreur.  Voltaire  (Discours en vers sur l'homme)",
    "Si l'erreur est une vérité provisoire, pourquoi la vérité ne serait-elle pas une erreur qui dure ?  Maurice Chapelan  (Main courante)",
    "Bien des erreurs sont nées d'une vérité dont on abuse.  Voltaire",
    "La vérité d'un homme ce sont ses erreurs.  Francis Picabia",
    "Dès que la majorité de mes contemporains choisit la même option que moi... j'en déduis que je suis forcément dans l'erreur. Si la raison, la sagesse et l'intelligence étaient majoritaires, ça se saurait.  Romain Guilleaumes  (Impertinences)",
    "Il arrive que l'erreur se trompe.  Georges Duhamel  (Défense des lettres)",
    "Le coeur est la source de toutes les erreurs dont nous avons besoin.  Bernard de Fontenelle  (Dialogues de morts)",
    "La source de nos chagrins est d'ordinaire dans nos erreurs.  Jean-Baptiste Massillon  (Sermons)",
    "Les plus courtes erreurs sont toujours les meilleures.  Jean-Baptiste Poquelin, dit Molière  (L'Etourdi)",
    "D'idées vraies en idées vraies et de clartés en clartés, le raisonnement peut n'arriver qu'à l'erreur.  Rivarol  (Discours sur l'homme intellectuel et moral)",
    "L'expérience est le nom que chacun donne à ses erreurs.  Oscar Wilde  (L'Eventail de Lady Windermere)",
    "L'erreur est facile à tous ; plus facile peut-être à celui qui croit savoir beaucoup.  Emile Chartier, dit Alain",
    "Un homme savant a compris un certain nombre de vérités. Un homme cultivé a compris un certain nombre d'erreurs. Et voilà toute la différence entre l'esprit droit et l'esprit juste.  Emile Chartier, dit Alain  (Vigiles de l'esprit)",
    "Discourir sur l'inexistence de Dieu, c'est faire beaucoup d'honneur au néant ou deviner son erreur.  Romain Guilleaumes  (Diverses idées)",
    "L'erreur de l'homme d'aujourd'hui est de vivre \"comme si Dieu n'existait pas\".  André Frossard",
    "L'homme est-il une erreur de Dieu, ou Dieu une erreur de l'homme ?  Friedrich Nietzsche",
    "L'erreur est humaine, persévérer dans l'erreur est diabolique.  Proverbe latin",
    "Toute secte, en quelque genre que ce puisse être, est le ralliement du doute et de l'erreur.  Voltaire  (Dictionnaire philosophique)",
    "N'interrompez jamais un ennemi qui est en train de faire une erreur.  Napoléon Bonaparte",
    "L'erreur est plus entêtée que la foi et n'examine pas ses croyances.  Marcel Proust  (A la recherche du temps perdu, La Prisonnière)",
    "Le métier des intellectuels consiste à commettre des erreurs afin de les éliminer une à une.  Romain Guilleaumes  (Diverses idées)",
    "Les parents d'aujourd'hui veulent être aimés de leurs enfants. Cette erreur les entraîne à toutes sortes de faiblesses et de facilités.  Jean Dutourd  (Le fond et la forme)",
    "Le rôle d'un ami, c'est de se trouver à votre côté quand vous êtes dans l'erreur puisque tout le monde sera à côté de vous quand vous aurez raison.  Mark Twain",
    "On ne pardonne pas à son ami ses erreurs, on ne les excuse pas non plus. On les comprend.  Philippe Soupault  (L'Amitié)",
    "Vérité dans un temps, erreur dans un autre.  Montesquieu",
    "L'avantage des médecins, c'est que lorsqu'ils commettent une erreur, ils l'enterrent tout de suite...  Alphonse Allais",
    "Des erreurs, j'en ai fait. D'abord, je suis né. Première erreur !  Woody Allen",
    "La jeunesse est une courte erreur, et la vieillesse un long regret.  Henri Duvernois",
    "L'âge mûr est le plus beau de tous. On est assez vieux pour reconnaître ses erreurs passées et encore assez jeune pour en commettre de nouvelles.  Maurice Chevalier",
    "L'erreur a créé beaucoup plus que la vérité.  Edouard Herriot",
    "Le pamphlet est l'arme de ceux qui ont découvert l'erreur, pas encore la vérité.  Gilbert Cesbron  (Journal sans date)",
    "L'erreur est aussi grande de se fier à tous que de se défier de tous.  Sénèque",
    "La hâte engendre en tout l'erreur, et de l'erreur sort bien souvent le désastre.  Hérodote  (Histoires)",
    "Les erreurs sont les portes de la découverte.  James Joyce",
    "Vérité dans un temps, erreur dans un autre.  Montesquieu  (Lettres persanes)",
    "Le désespoir est la plus grandes des erreurs.  Vauvenargues  (Réflexions et maximes)",
    "La Justice, c'es six mille ans d'erreurs judiciaires.  Robert Brasillach",
    "Une erreur originale vaut mieux qu'une vérité banale.  Fedor Dostoïevski",
    "Qui cherche plus que le nécessaire se livre à l'erreur.  Hazrat Ali",
    "L'erreur est la nuit des esprits et le piège de l'innocence.  Vauvenargues  (Réflexions et maximes)",
    "Rien ne nuit plus à une vérité qu'une erreur ancienne.  Goethe",
    "Une personne qui n'a jamais commis d'erreurs n'a jamais tenté d'innover.  Albert Einstein",
    "Nos goûts et nos passions nous dégradent plus que nos opinions et nos erreurs.  Rivarol  (L'esprit de Rivarol)",
    "Si vous fermez la porte à toutes les erreurs, la vérité restera dehors.  Rabindranàth Tagore",
    "La foule est une somme d'erreurs qu'il faut corriger.  Friedrich Nietzsche  (Mort parce que bête)",
    "C'est un péché de penser du mal des autres, mais c'est rarement une erreur.  Henri Louis Mencken",
    "La vérité de demain se nourrit de l'erreur d'hier.  Antoine de Saint-Exupéry  (Pilote de guerre)",
    "A l'heure du choix, il n'est d'erreur inévitable que lorsque le coeur supplée la raison.  Romain Guilleaumes  (Diverses idées)",
    "Voilà la grande erreur de toujours : s'imaginer que les êtres pensent ce qu'ils disent.  Jacques Lacan",
    "L'homme n'apprend vraiment qu'en reconnaissant ses propres erreurs.  Jean-Paul II  (Entrez dans l'espérance)",
    "Si les grands hommes n'avaient pas commis d'erreurs, nous ne saurions pas qu'ils ont existé.  Louis Scutenaire  (Mes inscriptions)",
    "Un \"loser\" ou un raté, c'est un être qui reste sourd à nos valeurs, servitudes et ambitions. A ses yeux, nous sommes également dans l'erreur.  Romain Guilleaumes  (Errance)",
    "N'est-il pas étrange de nous voir défendre plus farouchement nos erreurs que nos valeurs ?  Khalil Gibran  (Le sable et l'écume)",
];